name: umvvm_generator
description: "Source generators for Umvvm architecture library"
version: 1.0.0

publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  glob: ^2.1.2
  source_gen: ^1.4.0

  umvvm: 
    git: 
      url: https://gitlab.rdclr.ru/flutter/umvvm.git
      path: packages/umvvm
      branch: main

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.7
  build_config: ^1.1.1
  flutter_lints: ^3.0.1
flutter:
