name: umvvm_generator

description: Source generators for Umvvm architecture library annotations

version: 1.0.0

repository: https://github.com/red-collar-dev/umvvm
issue_tracker: https://github.com/red-collar-dev/umvvm/issues
documentation: https://github.com/red-collar-dev/umvvm/tree/main/packages/umvvm/doc
topics: [mvvm, state-management, di, navigation, codegen]

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  glob: ^2.1.2
  source_gen: ^1.5.0
  logging: ^1.2.0
  build: ^2.4.1
  path: ^1.8.0
  analyzer: ^6.4.1
  umvvm: ^1.0.1

dev_dependencies:
  build_runner: ^2.4.8
  build_config: ^1.1.1
  flutter_lints: ^3.0.1
  build_test: ^2.2.2
  test: ^1.25.0
flutter:
