name: example
description: Basic example
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  umvvm: 
    git: 
      url: https://gitlab.rdclr.ru/flutter/umvvm.git
      path: packages/umvvm
      branch: main

  dio: ^5.4.0
  dart_mappable: ^4.1.0

dev_dependencies:
  umvvm_generator: 
    path: ../../umvvm_generator

  build: ^2.4.1
  build_config: ^1.1.1
  build_runner: ^2.4.6
  flutter_lints: ^3.0.1
  dart_mappable_builder: ^4.1.0

flutter:
  uses-material-design: true