targets:
  $default:
    builders:
      collectors:
        enabled: true
      generators:
        enabled: true

builders:
  generators:
    import: "package:mvvm_redux/generators/builders.dart"
    builder_factories: ["generateMainApp", "generateMainApi"]
    build_extensions: { ".dart": [".mvvm.dart", ".api.dart"] }
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen:combining_builder"]
  collectors:
    import: "package:mvvm_redux/collectors/builders.dart"
    builder_factories: ["generateInstanceCollector"]
    build_extensions: { ".dart": [".main_app_generator.g.part", ".main_api_generator.g.part"] }
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen:combining_builder"]
    runs_before: ["generators|generators"]