targets:
  $default:
    builders:
      generators|annotations:
        enabled: true

builders:
  generators:
    target: ":streamservice-client-toolbox"
    import: "package:mvvm_redux/generators/builders.dart"
    builder_factories: ["generateMainApp"]
    build_extensions: { ".dart": [".g.dart"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]