name: mvvm_redux

description: Mvvm-Redux base classes

version: 1.3.0

publish_to: none

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ^3.7.12

dependencies:
  flutter:
    sdk: flutter
  
  dio: ^5.1.1
  intl: ^0.17.0
  pedantic: ^1.11.1
  async: ^2.10.0
  source_gen:

dev_dependencies:
  build_runner: ^2.2.2

flutter:

