name: mvvm_redux

description: Mvvm-Redux base classes

version: 1.3.0

publish_to: none

environment:
  sdk: ">=2.18.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  dio: ^5.3.2
  pedantic: ^1.11.1
  async: ^2.9.0
  source_gen: ^1.4.0

dev_dependencies:
  build_runner: ^2.4.6

flutter:

