name: mvvm_redux

description: Mvvm-Redux base classes

version: 1.3.0

publish_to: none

environment:
  sdk: ">=2.18.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  dio: ^5.1.2
  intl: ^0.18.0
  pedantic: ^1.11.1
  async: ^2.11.0
  source_gen:

dev_dependencies:
  build_runner: ^2.3.1

flutter:

