name: mvvm_redux

description: Mvvm-Redux base classes

version: 1.0.2

publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ^3.0.5

dependencies:
  flutter:
    sdk: flutter
  
  dio: ^4.0.6
  intl: ^0.17.0
  pedantic: ^1.11.1
  sticky_infinite_list: ^4.0.1
  async: ^2.6.1
  source_gen:

dev_dependencies:
  build_runner: ^2.0.0

flutter:

