name: umvvm

description: UMvvm base classes

version: 3.3.2

publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  dio: ^5.3.3
  pedantic: ^1.11.1
  async: ^2.11.0
  back_button_interceptor: ^7.0.0
  source_gen: ^1.4.0
  cancellation_token_hoc081098: ^1.0.0
  glob: ^2.1.2
  visibility_detector: ^0.4.0+2

dev_dependencies:
  build_runner: ^2.4.6
  build_config: ^1.1.1
  flutter_lints: ^3.0.0

flutter:

