name: mvvm_redux

description: Mvvm-Redux base classes

version: 2.1.0

publish_to: none

environment:
  sdk: ">=2.18.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  dio: ^5.3.2
  pedantic: ^1.11.1
  async: ^2.11.0
  back_button_interceptor: ^7.0.0
  source_gen: ^1.4.0
  cancellation_token_hoc081098: ^1.0.0
  freezed_annotation: ^2.4.1

dev_dependencies:
  build_runner: ^2.4.6
  build_config: ^1.1.1
  freezed: ^2.4.1

flutter:

