name: sample_database
description: Sample for toolbox
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

  mvvm_redux:
    path: ../../

  dio: ^5.1.1
  freezed_annotation: ^2.1.0
  shared_preferences: ^2.0.15
  objectbox: ^1.6.2
  objectbox_flutter_libs: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  integration_test:
    sdk: flutter

  json_serializable:
  build: ^2.2.1
  build_config: ^1.0.0
  build_runner: ^2.1.8
  freezed: ^2.1.0+1
  objectbox_generator: any
  test:

flutter:
  uses-material-design: true