name: umvvm

description: UMvvm architecture components

version: 1.0.0+1

repository: https://github.com/red-collar-dev/umvvm
issue_tracker: https://github.com/red-collar-dev/umvvm/issues
documentation: https://github.com/red-collar-dev/umvvm/tree/main/packages/umvvm/doc
topics: [mvvm, state-management, di, navigation]

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  dio: ^5.4.0
  async: ^2.11.0
  source_gen: ^1.5.0
  visibility_detector: ^0.4.0+2

dev_dependencies:
  build_runner: ^2.4.8
  build_config: ^1.1.1
  flutter_lints: ^3.0.1
  http_mock_adapter: ^0.6.1

  test: any
  flutter_test: 
    sdk: flutter
  integration_test: 
    sdk: flutter

flutter:

