name: sample_basic
description: Sample with basic interactor example and global navigation
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  umvvm:
    path: ../../

  dio: ^5.3.3
  freezed_annotation: ^2.4.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  integration_test:
    sdk: flutter

  json_serializable:
  build: ^2.4.1
  build_config: ^1.1.1
  build_runner: ^2.4.6
  flutter_lints: ^3.0.1
  freezed: ^2.4.1
  test:

flutter:
  uses-material-design: true