name: sample_navigation
description: Sample with NavigationInteractor and nested navigation
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  mvvm_redux:
    path: ../../

  dio: ^5.1.1
  freezed_annotation: ^2.1.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  integration_test:
    sdk: flutter

  json_serializable:
  build: ^2.3.1
  build_config: ^1.1.1
  build_runner: ^2.2.2
  freezed: ^2.1.0+1
  test:

flutter:
  uses-material-design: true